//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class NSBundle, NSString, TVSettingsPreferenceFacade;

@interface TVSettingsItemFactory : NSObject
{
    NSBundle *_bundle;	// 8 = 0x8
    NSString *_plistName;	// 16 = 0x10
    NSString *_appIdentifier;	// 24 = 0x18
    TVSettingsPreferenceFacade *_preferenceFacade;	// 32 = 0x20
}

+ (long long)_autocapitalizationTypeFromString:(id)arg1;	// IMP=0x000000010003396c
+ (long long)_autocorrectionTypeFromString:(id)arg1;	// IMP=0x00000001000338f8
+ (long long)_keyboardTypeFromString:(id)arg1;	// IMP=0x0000000100033844
+ (_Bool)_specifierSupported:(id)arg1;	// IMP=0x00000001000337cc
@property(retain, nonatomic) TVSettingsPreferenceFacade *preferenceFacade; // @synthesize preferenceFacade=_preferenceFacade;
@property(copy, nonatomic) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(copy, nonatomic) NSString *plistName; // @synthesize plistName=_plistName;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;

- (id)privacyItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100033708
- (id)titleItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100033374
- (id)toggleItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100032eec
- (id)longTextItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100032bdc
- (id)textItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00000001000328bc
- (id)sliderItemFromSpecifierDictionary:(id)arg1;	// IMP=0x000000010003285c
- (id)radioGroupFromSpecifierDictionary:(id)arg1;	// IMP=0x00000001000323b8
- (id)multiValueItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100031e10
- (id)groupFromSpecifierDictionary:(id)arg1 withItems:(id)arg2;	// IMP=0x0000000100031bc4
- (id)childPaneItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0000000100031858
- (id)initWithBundle:(id)arg1 appIdentifier:(id)arg2 containerPath:(id)arg3 plistName:(id)arg4;	// IMP=0x00000001000316f0

@end

